/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        footer: "url('/footer_bg.png')",
        eap_service: "url('/src/assets/images/EAP/bg-eap_hero.png')",
        career: "url('/src/assets/images/career/bg-career.jpg')",
      },
      fontFamily: {
        sora: ["Sora", "sans-serif"],
        archivo: ["Archivo", "sans-serif"],
        switzerRegular: ["SwitzerRegular", "sans-serif"],
        switzerSemiBold: ["SwitzerSemiBold", "sans-serif"],
        switzerBold: ["SwitzerBold", "sans-serif"],
        switzerExtraBold: ["SwitzerExtraBold", "sans-serif"],
        mulish: ["Mulish", "sans-serif"],
      },
      fontSize: {
        tinyS: ["10.58px", "175.87px"],
        tiny: ["12.35px", "17.64px"],
        small: ["10px", "16px"],
        baseSS: ["12.5px", "20px"],
        baseSm: ["13px", "20px"],
        slightlySmall: ["14px", "20px"],
        baseS: ["14px", "22px"],
        baseSmall: ["15px", "24px"],
        baseSmallM: ["16px", "26px"],
        baseSmalls: ["17px", "24px"],
        semiSmall: ["17px", "28px"],
        medium: ["17px", "32px"],
        mediumB: ["19px", "32px"],
        mediumS: ["20px", "32px"],
        mediumL: ["20px", "44px"],
        mediumP: ["22px", "44px"],
        MediumX: ["23px", "30px"],
        semiMedium: ["24px", "30px"],
        semiBase: ["24px", "44px"],
        semiBaseL: ["30px", "40px"],
        large: ["32px", "38px"],
        largeX: ["32px", "44px"],
        LargeXX: ["33px", "45px"],
        semiLargeXX: ["35px", "45px"],
        semiLarge: ["40px", "48px"],
        extraLarge: ["57px", "70px"],
      },
      colors: {
        neutral: {
          "gray-25": "#FAFAFA",
          "gray-800": "#1F242F",
          "gray-900": "#161B26",
        },
        brand: {
          primary: {
            default: "#006AB4",
            lightGreen: "#02BCB6",
            darkGreen: "#2B892B",
            gray: "#F8F7F2",
            black: "#09090B",
            green: "#0C270C",
            disable: "#B7B7C3",
            destructive: "#E35454",
            white: "#FFFFFF",
          },
          secondary: {
            grey: "#807F94",
            lightGrey: "#E0E0E6",
            darkGrey: "#2D384D",
            MidDarkGrey: "#31405B",
            extraLightBlue: "#445C85",
            customSkyBlue800: "#006AB4",
            customSkyBlue900: "#002E4E",
            customGrey950: "#161B26",
            customGrey900: "#30394A",
            customGrey800: "#1B444D",
            customBlue900: "#4A0E9E",
            customBlue800: "#3C6096",
            customGreen900: "#31822F",
            customGreen800: "#1C9F60",
            customBlue700: "#2F3782",
            customBlue600: "#365CA9",
            customPurple900: "#682076",
            customPurple800: "#9715B1",
            buttonText: "#05729F",
          },
        },
      },
    },
  },
  plugins: [],
};
